apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-apache
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      containers:
      - name: php-apache
        image: k8s.gcr.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 200m

# kubectl apply -f php-apache.yaml
# kubectl expose deploy php-apache --port=80 --target-port=80
# kubectl autoscale deployment php-apache --cpu-percent=50 --min=1 --max=10
# kubectl get hpa

# load testing command: 
# kubectl run -i --tty load-generator --rm --image=busybox:1.28 --restart=Never -- /bin/sh -c "while sleep 0.01; do wget -q -O- http://php-apache; done"


# in another terminal: 
# kubectl get hpa php-apache --watch
# kubectl get deploy php-apache --watch
# kubectl top pods

