apiVersion: v1
kind: Pod
metadata:
  name: pv-pod
spec:
  containers:
  - name: web
    image: nginx
    ports:
      - containerPort: 80
    
    volumeMounts:
      - name: storage
        mountPath: /usr/share/nginx/html
    
  volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: pvc-demo
