apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
  namespace: default
  name: pod-reader 
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]


    # reference: https://kubernetes.io/docs/reference/access-authn-authz/rbac/