# apiVersion: v1
# kind: Pod
# metadata:
#   name: secret-demo-pod
# spec:
#   containers:
#   - name: demo
#     image: nginx:1.14.2
#     env:
#     - name: DB_USER
#       valueFrom: 
#         secretKeyRef:
#           name: db-secret
#           key: username
#     - name: DB_PASS
#       valueFrom: 
#         secretKeyRef:
#           name: db-secret
#           key: password

apiVersion: v1
kind: Pod
metadata:
  name: secret-vol-pod
spec:
  containers:
  - name: demo
    image: nginx
    volumeMounts:
      - name: secret-vol
        mountPath:  "/etc/secret-data"
        readOnly: true
  volumes:
    - name: secret-vol
      secret:
        secretName: db-secret